import type { CurrencyMetadata } from "@openrates/schemas";

export const CURRENCIES: readonly CurrencyMetadata[] = [
  {
    code: "USD",
    numericCode: "840",
    name: "United States Dollar",
    minorUnits: 2,
    status: "active",
    countries: ["United States", "Ecuador", "El Salvador", "Panama"],
    symbols: ["$", "US$"],
    aliases: ["us dollar", "american dollar", "united states dollar"],
  },
  {
    code: "EUR",
    numericCode: "978",
    name: "Euro",
    minorUnits: 2,
    status: "active",
    countries: ["Eurozone", "Germany", "France", "Spain", "Italy"],
    symbols: ["€"],
    aliases: ["euro"],
  },
  {
    code: "JPY",
    numericCode: "392",
    name: "Japanese Yen",
    minorUnits: 0,
    status: "active",
    countries: ["Japan"],
    symbols: ["¥", "円"],
    aliases: ["yen", "japanese yen"],
  },
  {
    code: "GBP",
    numericCode: "826",
    name: "Pound Sterling",
    minorUnits: 2,
    status: "active",
    countries: ["United Kingdom"],
    symbols: ["£"],
    aliases: ["british pound", "pound sterling", "sterling", "quid"],
  },
  {
    code: "CHF",
    numericCode: "756",
    name: "Swiss Franc",
    minorUnits: 2,
    status: "active",
    countries: ["Switzerland", "Liechtenstein"],
    symbols: ["CHF", "Fr"],
    aliases: ["swiss franc", "swissie"],
  },
  {
    code: "AUD",
    numericCode: "036",
    name: "Australian Dollar",
    minorUnits: 2,
    status: "active",
    countries: ["Australia"],
    symbols: ["A$", "$"],
    aliases: ["australian dollar", "aussie dollar", "aussie"],
  },
  {
    code: "CAD",
    numericCode: "124",
    name: "Canadian Dollar",
    minorUnits: 2,
    status: "active",
    countries: ["Canada"],
    symbols: ["C$", "$"],
    aliases: ["canadian dollar", "loonie"],
  },
  {
    code: "NZD",
    numericCode: "554",
    name: "New Zealand Dollar",
    minorUnits: 2,
    status: "active",
    countries: ["New Zealand"],
    symbols: ["NZ$", "$"],
    aliases: ["new zealand dollar", "kiwi dollar", "kiwi"],
  },
  {
    code: "CNY",
    numericCode: "156",
    name: "Chinese Yuan Renminbi",
    minorUnits: 2,
    status: "active",
    countries: ["China"],
    symbols: ["¥", "元", "CN¥"],
    aliases: ["yuan", "renminbi", "chinese yuan", "rmb"],
  },
  {
    code: "HKD",
    numericCode: "344",
    name: "Hong Kong Dollar",
    minorUnits: 2,
    status: "active",
    countries: ["Hong Kong"],
    symbols: ["HK$", "$"],
    aliases: ["hong kong dollar"],
  },
  {
    code: "SGD",
    numericCode: "702",
    name: "Singapore Dollar",
    minorUnits: 2,
    status: "active",
    countries: ["Singapore"],
    symbols: ["S$", "$"],
    aliases: ["singapore dollar"],
  },
  {
    code: "TWD",
    numericCode: "901",
    name: "New Taiwan Dollar",
    minorUnits: 2,
    status: "active",
    countries: ["Taiwan"],
    symbols: ["NT$", "$"],
    aliases: ["taiwan dollar", "new taiwan dollar"],
  },
  {
    code: "INR",
    numericCode: "356",
    name: "Indian Rupee",
    minorUnits: 2,
    status: "active",
    countries: ["India"],
    symbols: ["₹", "Rs"],
    aliases: ["indian rupee"],
  },
  {
    code: "PKR",
    numericCode: "586",
    name: "Pakistani Rupee",
    minorUnits: 2,
    status: "active",
    countries: ["Pakistan"],
    symbols: ["₨", "Rs"],
    aliases: ["pakistani rupee"],
  },
  {
    code: "LKR",
    numericCode: "144",
    name: "Sri Lankan Rupee",
    minorUnits: 2,
    status: "active",
    countries: ["Sri Lanka"],
    symbols: ["₨", "Rs"],
    aliases: ["sri lankan rupee"],
  },
  {
    code: "NPR",
    numericCode: "524",
    name: "Nepalese Rupee",
    minorUnits: 2,
    status: "active",
    countries: ["Nepal"],
    symbols: ["₨", "Rs"],
    aliases: ["nepalese rupee"],
  },
  {
    code: "MUR",
    numericCode: "480",
    name: "Mauritian Rupee",
    minorUnits: 2,
    status: "active",
    countries: ["Mauritius"],
    symbols: ["₨", "Rs"],
    aliases: ["mauritian rupee"],
  },
  {
    code: "IDR",
    numericCode: "360",
    name: "Indonesian Rupiah",
    minorUnits: 2,
    status: "active",
    countries: ["Indonesia"],
    symbols: ["Rp"],
    aliases: ["indonesian rupiah", "rupiah"],
  },
  {
    code: "MYR",
    numericCode: "458",
    name: "Malaysian Ringgit",
    minorUnits: 2,
    status: "active",
    countries: ["Malaysia"],
    symbols: ["RM"],
    aliases: ["malaysian ringgit", "ringgit"],
  },
  {
    code: "THB",
    numericCode: "764",
    name: "Thai Baht",
    minorUnits: 2,
    status: "active",
    countries: ["Thailand"],
    symbols: ["฿"],
    aliases: ["thai baht", "baht"],
  },
  {
    code: "PHP",
    numericCode: "608",
    name: "Philippine Peso",
    minorUnits: 2,
    status: "active",
    countries: ["Philippines"],
    symbols: ["₱"],
    aliases: ["philippine peso"],
  },
  {
    code: "KRW",
    numericCode: "410",
    name: "South Korean Won",
    minorUnits: 0,
    status: "active",
    countries: ["South Korea"],
    symbols: ["₩"],
    aliases: ["won", "south korean won", "korean won"],
  },
  {
    code: "VND",
    numericCode: "704",
    name: "Vietnamese Dong",
    minorUnits: 0,
    status: "active",
    countries: ["Vietnam"],
    symbols: ["₫"],
    aliases: ["vietnamese dong", "dong"],
  },
  {
    code: "RUB",
    numericCode: "643",
    name: "Russian Ruble",
    minorUnits: 2,
    status: "active",
    countries: ["Russia"],
    symbols: ["₽"],
    aliases: ["ruble", "rouble", "russian ruble"],
  },
  {
    code: "TRY",
    numericCode: "949",
    name: "Turkish Lira",
    minorUnits: 2,
    status: "active",
    countries: ["Turkey"],
    symbols: ["₺", "TL"],
    aliases: ["turkish lira", "lira", "new turkish lira"],
  },
  {
    code: "BRL",
    numericCode: "986",
    name: "Brazilian Real",
    minorUnits: 2,
    status: "active",
    countries: ["Brazil"],
    symbols: ["R$"],
    aliases: ["brazilian real", "real"],
  },
  {
    code: "MXN",
    numericCode: "484",
    name: "Mexican Peso",
    minorUnits: 2,
    status: "active",
    countries: ["Mexico"],
    symbols: ["Mex$", "$"],
    aliases: ["mexican peso"],
  },
  {
    code: "ARS",
    numericCode: "032",
    name: "Argentine Peso",
    minorUnits: 2,
    status: "active",
    countries: ["Argentina"],
    symbols: ["$"],
    aliases: ["argentine peso", "argentinian peso"],
  },
  {
    code: "CLP",
    numericCode: "152",
    name: "Chilean Peso",
    minorUnits: 0,
    status: "active",
    countries: ["Chile"],
    symbols: ["$"],
    aliases: ["chilean peso"],
  },
  {
    code: "COP",
    numericCode: "170",
    name: "Colombian Peso",
    minorUnits: 2,
    status: "active",
    countries: ["Colombia"],
    symbols: ["$"],
    aliases: ["colombian peso"],
  },
  {
    code: "UYU",
    numericCode: "858",
    name: "Uruguayan Peso",
    minorUnits: 2,
    status: "active",
    countries: ["Uruguay"],
    symbols: ["$U"],
    aliases: ["uruguayan peso"],
  },
  {
    code: "DOP",
    numericCode: "214",
    name: "Dominican Peso",
    minorUnits: 2,
    status: "active",
    countries: ["Dominican Republic"],
    symbols: ["RD$"],
    aliases: ["dominican peso"],
  },
  {
    code: "CUP",
    numericCode: "192",
    name: "Cuban Peso",
    minorUnits: 2,
    status: "active",
    countries: ["Cuba"],
    symbols: ["$"],
    aliases: ["cuban peso"],
  },
  {
    code: "ZAR",
    numericCode: "710",
    name: "South African Rand",
    minorUnits: 2,
    status: "active",
    countries: ["South Africa"],
    symbols: ["R"],
    aliases: ["rand", "south african rand"],
  },
  {
    code: "SEK",
    numericCode: "752",
    name: "Swedish Krona",
    minorUnits: 2,
    status: "active",
    countries: ["Sweden"],
    symbols: ["kr"],
    aliases: ["swedish krona"],
  },
  {
    code: "NOK",
    numericCode: "578",
    name: "Norwegian Krone",
    minorUnits: 2,
    status: "active",
    countries: ["Norway"],
    symbols: ["kr"],
    aliases: ["norwegian krone"],
  },
  {
    code: "DKK",
    numericCode: "208",
    name: "Danish Krone",
    minorUnits: 2,
    status: "active",
    countries: ["Denmark"],
    symbols: ["kr"],
    aliases: ["danish krone"],
  },
  {
    code: "ISK",
    numericCode: "352",
    name: "Icelandic Krona",
    minorUnits: 0,
    status: "active",
    countries: ["Iceland"],
    symbols: ["kr"],
    aliases: ["icelandic krona"],
  },
  {
    code: "PLN",
    numericCode: "985",
    name: "Polish Zloty",
    minorUnits: 2,
    status: "active",
    countries: ["Poland"],
    symbols: ["zł"],
    aliases: ["polish zloty", "zloty"],
  },
  {
    code: "CZK",
    numericCode: "203",
    name: "Czech Koruna",
    minorUnits: 2,
    status: "active",
    countries: ["Czechia"],
    symbols: ["Kč"],
    aliases: ["czech koruna", "koruna"],
  },
  {
    code: "HUF",
    numericCode: "348",
    name: "Hungarian Forint",
    minorUnits: 2,
    status: "active",
    countries: ["Hungary"],
    symbols: ["Ft"],
    aliases: ["hungarian forint", "forint"],
  },
  {
    code: "RON",
    numericCode: "946",
    name: "Romanian Leu",
    minorUnits: 2,
    status: "active",
    countries: ["Romania"],
    symbols: ["lei"],
    aliases: ["romanian leu", "leu"],
  },
  {
    code: "BGN",
    numericCode: "975",
    name: "Bulgarian Lev",
    minorUnits: 2,
    status: "active",
    countries: ["Bulgaria"],
    symbols: ["лв"],
    aliases: ["bulgarian lev", "lev"],
  },
  {
    code: "UAH",
    numericCode: "980",
    name: "Ukrainian Hryvnia",
    minorUnits: 2,
    status: "active",
    countries: ["Ukraine"],
    symbols: ["₴"],
    aliases: ["ukrainian hryvnia", "hryvnia"],
  },
  {
    code: "SAR",
    numericCode: "682",
    name: "Saudi Riyal",
    minorUnits: 2,
    status: "active",
    countries: ["Saudi Arabia"],
    symbols: ["﷼", "SR"],
    aliases: ["saudi riyal", "saudi arabian riyal"],
  },
  {
    code: "AED",
    numericCode: "784",
    name: "United Arab Emirates Dirham",
    minorUnits: 2,
    status: "active",
    countries: ["United Arab Emirates"],
    symbols: ["د.إ", "AED"],
    aliases: ["uae dirham", "emirati dirham", "dirham"],
  },
  {
    code: "QAR",
    numericCode: "634",
    name: "Qatari Riyal",
    minorUnits: 2,
    status: "active",
    countries: ["Qatar"],
    symbols: ["﷼", "QR"],
    aliases: ["qatari riyal"],
  },
  {
    code: "KWD",
    numericCode: "414",
    name: "Kuwaiti Dinar",
    minorUnits: 3,
    status: "active",
    countries: ["Kuwait"],
    symbols: ["د.ك", "KD"],
    aliases: ["kuwaiti dinar"],
  },
  {
    code: "BHD",
    numericCode: "048",
    name: "Bahraini Dinar",
    minorUnits: 3,
    status: "active",
    countries: ["Bahrain"],
    symbols: ["ب.د", "BD"],
    aliases: ["bahraini dinar"],
  },
  {
    code: "OMR",
    numericCode: "512",
    name: "Omani Rial",
    minorUnits: 3,
    status: "active",
    countries: ["Oman"],
    symbols: ["ر.ع.", "RO"],
    aliases: ["omani rial"],
  },
  {
    code: "JOD",
    numericCode: "400",
    name: "Jordanian Dinar",
    minorUnits: 3,
    status: "active",
    countries: ["Jordan"],
    symbols: ["د.ا", "JD"],
    aliases: ["jordanian dinar"],
  },
  {
    code: "IQD",
    numericCode: "368",
    name: "Iraqi Dinar",
    minorUnits: 3,
    status: "active",
    countries: ["Iraq"],
    symbols: ["ع.د"],
    aliases: ["iraqi dinar"],
  },
  {
    code: "LYD",
    numericCode: "434",
    name: "Libyan Dinar",
    minorUnits: 3,
    status: "active",
    countries: ["Libya"],
    symbols: ["ل.د", "LD"],
    aliases: ["libyan dinar"],
  },
  {
    code: "TND",
    numericCode: "788",
    name: "Tunisian Dinar",
    minorUnits: 3,
    status: "active",
    countries: ["Tunisia"],
    symbols: ["د.ت", "DT"],
    aliases: ["tunisian dinar"],
  },
  {
    code: "DZD",
    numericCode: "012",
    name: "Algerian Dinar",
    minorUnits: 2,
    status: "active",
    countries: ["Algeria"],
    symbols: ["د.ج", "DA"],
    aliases: ["algerian dinar"],
  },
  {
    code: "RSD",
    numericCode: "941",
    name: "Serbian Dinar",
    minorUnits: 2,
    status: "active",
    countries: ["Serbia"],
    symbols: ["дин", "RSD"],
    aliases: ["serbian dinar"],
  },
  {
    code: "IRR",
    numericCode: "364",
    name: "Iranian Rial",
    minorUnits: 2,
    status: "active",
    countries: ["Iran"],
    symbols: ["﷼"],
    aliases: ["iranian rial"],
  },
  {
    code: "YER",
    numericCode: "886",
    name: "Yemeni Rial",
    minorUnits: 2,
    status: "active",
    countries: ["Yemen"],
    symbols: ["﷼"],
    aliases: ["yemeni rial"],
  },
  {
    code: "ILS",
    numericCode: "376",
    name: "Israeli New Shekel",
    minorUnits: 2,
    status: "active",
    countries: ["Israel"],
    symbols: ["₪"],
    aliases: ["israeli shekel", "shekel", "new shekel"],
  },
  {
    code: "EGP",
    numericCode: "818",
    name: "Egyptian Pound",
    minorUnits: 2,
    status: "active",
    countries: ["Egypt"],
    symbols: ["E£", "ج.م"],
    aliases: ["egyptian pound"],
  },
  {
    code: "LBP",
    numericCode: "422",
    name: "Lebanese Pound",
    minorUnits: 2,
    status: "active",
    countries: ["Lebanon"],
    symbols: ["ل.ل", "L£"],
    aliases: ["lebanese pound"],
  },
  {
    code: "SDG",
    numericCode: "938",
    name: "Sudanese Pound",
    minorUnits: 2,
    status: "active",
    countries: ["Sudan"],
    symbols: ["ج.س."],
    aliases: ["sudanese pound"],
  },
  {
    code: "SYP",
    numericCode: "760",
    name: "Syrian Pound",
    minorUnits: 2,
    status: "active",
    countries: ["Syria"],
    symbols: ["£S", "ل.س"],
    aliases: ["syrian pound"],
  },
  {
    code: "AFN",
    numericCode: "971",
    name: "Afghan Afghani",
    minorUnits: 2,
    status: "active",
    countries: ["Afghanistan"],
    symbols: ["؋", "Af"],
    aliases: ["afghani", "afghan afghani", "afghan"],
  },
  {
    code: "MAD",
    numericCode: "504",
    name: "Moroccan Dirham",
    minorUnits: 2,
    status: "active",
    countries: ["Morocco"],
    symbols: ["د.م.", "DH"],
    aliases: ["moroccan dirham"],
  },
  {
    code: "NGN",
    numericCode: "566",
    name: "Nigerian Naira",
    minorUnits: 2,
    status: "active",
    countries: ["Nigeria"],
    symbols: ["₦"],
    aliases: ["nigerian naira", "naira"],
  },
  {
    code: "GHS",
    numericCode: "936",
    name: "Ghanaian Cedi",
    minorUnits: 2,
    status: "active",
    countries: ["Ghana"],
    symbols: ["₵", "GH₵"],
    aliases: ["ghanaian cedi", "cedi"],
  },
  {
    code: "KES",
    numericCode: "404",
    name: "Kenyan Shilling",
    minorUnits: 2,
    status: "active",
    countries: ["Kenya"],
    symbols: ["KSh"],
    aliases: ["kenyan shilling"],
  },
  {
    code: "TZS",
    numericCode: "834",
    name: "Tanzanian Shilling",
    minorUnits: 2,
    status: "active",
    countries: ["Tanzania"],
    symbols: ["TSh"],
    aliases: ["tanzanian shilling"],
  },
  {
    code: "UGX",
    numericCode: "800",
    name: "Ugandan Shilling",
    minorUnits: 0,
    status: "active",
    countries: ["Uganda"],
    symbols: ["USh"],
    aliases: ["ugandan shilling"],
  },
  {
    code: "XOF",
    numericCode: "952",
    name: "West African CFA Franc",
    minorUnits: 0,
    status: "active",
    countries: ["Senegal", "Ivory Coast", "Mali", "Benin"],
    symbols: ["CFA", "F.CFA"],
    aliases: ["west african cfa franc", "cfa franc"],
  },
  {
    code: "XAF",
    numericCode: "950",
    name: "Central African CFA Franc",
    minorUnits: 0,
    status: "active",
    countries: ["Cameroon", "Chad", "Gabon", "Congo"],
    symbols: ["FCFA"],
    aliases: ["central african cfa franc"],
  },
  {
    code: "XPF",
    numericCode: "953",
    name: "CFP Franc",
    minorUnits: 0,
    status: "active",
    countries: ["French Polynesia", "New Caledonia"],
    symbols: ["₣", "F"],
    aliases: ["cfp franc", "pacific franc"],
  },
  {
    code: "BDT",
    numericCode: "050",
    name: "Bangladeshi Taka",
    minorUnits: 2,
    status: "active",
    countries: ["Bangladesh"],
    symbols: ["৳"],
    aliases: ["bangladeshi taka", "taka"],
  },
  {
    code: "TRL",
    name: "Old Turkish Lira",
    minorUnits: 0,
    status: "retired",
    countries: ["Turkey"],
    symbols: ["TL"],
    aliases: ["old turkish lira", "former turkish lira"],
    retiredAt: "2005-01-01",
    replacedBy: "TRY",
  },
  {
    code: "DEM",
    name: "German Mark",
    minorUnits: 2,
    status: "retired",
    countries: ["Germany"],
    symbols: ["DM"],
    aliases: ["german mark", "deutsche mark", "deutschmark"],
    retiredAt: "2002-03-01",
    replacedBy: "EUR",
  },
  {
    code: "FRF",
    name: "French Franc",
    minorUnits: 2,
    status: "retired",
    countries: ["France"],
    symbols: ["₣", "F"],
    aliases: ["french franc"],
    retiredAt: "2002-03-01",
    replacedBy: "EUR",
  },
  {
    code: "ITL",
    name: "Italian Lira",
    minorUnits: 0,
    status: "retired",
    countries: ["Italy"],
    symbols: ["₤", "L"],
    aliases: ["italian lira"],
    retiredAt: "2002-03-01",
    replacedBy: "EUR",
  },
];
